### ISSUE TITLE
Specification of metadata

### ISSUE THREAD

**Issue by juliohm** [shubhank-saxena/WellIO.jl#3]
The LAS format consists of a header with metadata plus a table with log measurements.

Please report here the sections of the header in versions 1.2 and 2.0 of the standard. In this report, please make sure to explain how you plan to parse the header to consume the metadata.

**Comment by shubhank-saxena** [comment]
This link clearly describes the specifications and components of LAS version 1.2
https://www.cwls.org/wp-content/uploads/2014/09/LAS12_Standards.txt

This link clearly describes the specification and components of LAS version 2.0
https://www.cwls.org/wp-content/uploads/2017/02/Las2_Update_Feb2017.pdf

**Comment by shubhank-saxena** [comment]
Plan of Action 
 - Use FileIO and write our own custom function to open the file
 - Dump the data in machine-readable form
 - Identify and split data into Metas and actual Data (on the basis of identifier flags like ~A)
 - Parse the differentiated data into tables struct using Tables.jl
 - Make sure to write methods to enable specific data call

**Comment by shubhank-saxena** [comment]
**Header Parsing** 
The Standard LAS 1.2 has 2 types of identifiers to parse data - 
    - Tilde (~) 
    - Flags

1. Tilde (~)
    -   ~V	- contains version and wrap mode information
    - 	~W	- contains well identification
    - 	~C	- contains curve information
    - 	~P	- contains parameters or constants
    - 	~O	- contains other information such as comments
    - 	~A	- contains ASCII log data

**Comment by juliohm** [comment]
The specification allows multiple sections of a given type? For example multiple `~A` sections in the same file?

What is the data structure you are planning to use to store the metadata? Try to draft a Julia `struct` with fields here so that we can converge on a good design.

**Comment by juliohm** [comment]
You can write this proposal in the form of a PR for review.
